language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
env:
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"
    - DJANGO_PACKAGE="Django<1.10"

matrix:
  exclude:
  - python: "2.6"
    env: DJANGO_PACKAGE="Django>=1.7,<1.8"
  - python: "2.6"
    env: DJANGO_PACKAGE="Django>=1.8,<1.9"
  - python: "2.6"
    env: DJANGO_PACKAGE="Django<1.10"
  - python: "3.2"
    env: DJANGO_PACKAGE="Django<1.10"
  - python: "3.3"
    env: DJANGO_PACKAGE="Django<1.10"
  - python: "3.4"
    env: DJANGO_PACKAGE="Django>=1.6,<1.7"

install:
    - pip install --pre $DJANGO_PACKAGE
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script: python setup.py test
