language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
env:
    - DJANGO_PACKAGE="Django>=1.7,<1.8"
    - DJANGO_PACKAGE="Django>=1.8,<1.9"

install:
    - pip install $DJANGO_PACKAGE --use-mirrors
script: python setup.py test
